In [ ]:
import pandas as pd
import numpy as np
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

df

                   A         B         C         D
2013-01-01  2.438309 -0.533176  1.889585  0.768839
2013-01-02 -1.278178  1.980355  0.087232  0.257254
2013-01-03  0.793269  0.813440  0.397283 -0.549010
2013-01-04  0.456985 -1.824791  0.705465  0.239551
2013-01-05 -0.909268  1.096913 -0.731259 -0.887379
2013-01-06  0.580815  1.291639 -0.423542  1.049427

In [ ]:
import pandas as pd
import numpy as np
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)


df2
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [ ]:
df.head()

                   A         B         C         D
2013-01-01  2.438309 -0.533176  1.889585  0.768839
2013-01-02 -1.278178  1.980355  0.087232  0.257254
2013-01-03  0.793269  0.813440  0.397283 -0.549010
2013-01-04  0.456985 -1.824791  0.705465  0.239551
2013-01-05 -0.909268  1.096913 -0.731259 -0.887379

In [ ]:
df.tail(2)

                   A         B         C         D
2013-01-05 -0.909268  1.096913 -0.731259 -0.887379
2013-01-06  0.580815  1.291639 -0.423542  1.049427

In [ ]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df.to_numpy()

array([[ 2.43830855, -0.53317583,  1.88958463,  0.76883928],
       [-1.27817804,  1.98035469,  0.0872317 ,  0.25725371],
       [ 0.79326943,  0.81344022,  0.39728256, -0.54900962],
       [ 0.45698507, -1.82479116,  0.70546508,  0.23955136],
       [-0.90926817,  1.09691342, -0.73125909, -0.88737896],
       [ 0.58081482,  1.29163948, -0.42354221,  1.04942741]])

In [ ]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [ ]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

displays quick Summary

In [ ]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.346989  0.470730  0.320794  0.146447
std    1.331083  1.395683  0.930627  0.745137
min   -1.278178 -1.824791 -0.731259 -0.887379
25%   -0.567705 -0.196522 -0.295849 -0.351869
50%    0.518900  0.955177  0.242257  0.248403
75%    0.740156  1.242958  0.628419  0.640943
max    2.438309  1.980355  1.889585  1.049427

Transposing your data:

In [ ]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    2.438309   -1.278178    0.793269    0.456985   -0.909268    0.580815
B   -0.533176    1.980355    0.813440   -1.824791    1.096913    1.291639
C    1.889585    0.087232    0.397283    0.705465   -0.731259   -0.423542
D    0.768839    0.257254   -0.549010    0.239551   -0.887379    1.049427

DataFrame.sort_index() sorts by an axis:

In [ ]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01  0.768839  1.889585 -0.533176  2.438309
2013-01-02  0.257254  0.087232  1.980355 -1.278178
2013-01-03 -0.549010  0.397283  0.813440  0.793269
2013-01-04  0.239551  0.705465 -1.824791  0.456985
2013-01-05 -0.887379 -0.731259  1.096913 -0.909268
2013-01-06  1.049427 -0.423542  1.291639  0.580815

DataFrame.sort_values() sorts by values:

In [ ]:
df.sort_values(by="B")

                   A         B         C         D
2013-01-04  0.456985 -1.824791  0.705465  0.239551
2013-01-01  2.438309 -0.533176  1.889585  0.768839
2013-01-03  0.793269  0.813440  0.397283 -0.549010
2013-01-05 -0.909268  1.096913 -0.731259 -0.887379
2013-01-06  0.580815  1.291639 -0.423542  1.049427
2013-01-02 -1.278178  1.980355  0.087232  0.257254

passing a single label selects a columns and yields a Series equivalent to df.A:

In [ ]:
df["A"]

2013-01-01    2.438309
2013-01-02   -1.278178
2013-01-03    0.793269
2013-01-04    0.456985
2013-01-05   -0.909268
2013-01-06    0.580815
Freq: D, Name: A, dtype: float64

For a DataFrame, passing a slice : selects matching rows:

In [ ]:
df[0:3]

                   A         B         C         D
2013-01-01  2.438309 -0.533176  1.889585  0.768839
2013-01-02 -1.278178  1.980355  0.087232  0.257254
2013-01-03  0.793269  0.813440  0.397283 -0.549010

In [ ]:
df["20130102":"20130104"]

                   A         B         C         D
2013-01-02 -1.278178  1.980355  0.087232  0.257254
2013-01-03  0.793269  0.813440  0.397283 -0.549010
2013-01-04  0.456985 -1.824791  0.705465  0.239551

Selecting a row matching a label:

In [ ]:
df.loc[dates[0]]

A    2.438309
B   -0.533176
C    1.889585
D    0.768839
Name: 2013-01-01 00:00:00, dtype: float64

Selecting all rows (:) with a select column labels:

In [ ]:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01  2.438309 -0.533176
2013-01-02 -1.278178  1.980355
2013-01-03  0.793269  0.813440
2013-01-04  0.456985 -1.824791
2013-01-05 -0.909268  1.096913
2013-01-06  0.580815  1.291639

For label slicing, both endpoints are included:

In [ ]:
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02 -1.278178  1.980355
2013-01-03  0.793269  0.813440
2013-01-04  0.456985 -1.824791

In [ ]:
df.loc[dates[0], "A"]

np.float64(2.438308551754381)

In [ ]:
df.at[dates[0], "A"]

np.float64(2.438308551754381)

In [ ]:
df.iloc[3]

A    0.456985
B   -1.824791
C    0.705465
D    0.239551
Name: 2013-01-04 00:00:00, dtype: float64

In [ ]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  0.456985 -1.824791
2013-01-05 -0.909268  1.096913

In [ ]:
df.iloc[[1, 2, 4], [0, 2]]

                   A         C
2013-01-02 -1.278178  0.087232
2013-01-03  0.793269  0.397283
2013-01-05 -0.909268 -0.731259

In [ ]:
df.iloc[1:3, :]

                   A         B         C         D
2013-01-02 -1.278178  1.980355  0.087232  0.257254
2013-01-03  0.793269  0.813440  0.397283 -0.549010

In [ ]:
df.iloc[:, 1:3]

                   B         C
2013-01-01 -0.533176  1.889585
2013-01-02  1.980355  0.087232
2013-01-03  0.813440  0.397283
2013-01-04 -1.824791  0.705465
2013-01-05  1.096913 -0.731259
2013-01-06  1.291639 -0.423542

In [ ]:
df.iloc[1, 1]

np.float64(1.9803546903459956)

In [ ]:
df.iat[1, 1]

np.float64(1.9803546903459956)

In [ ]:
df[df["A"] > 0]

                   A         B         C         D
2013-01-01  2.438309 -0.533176  1.889585  0.768839
2013-01-03  0.793269  0.813440  0.397283 -0.549010
2013-01-04  0.456985 -1.824791  0.705465  0.239551
2013-01-06  0.580815  1.291639 -0.423542  1.049427

In [ ]:
df[df > 0]

                   A         B         C         D
2013-01-01  2.438309       NaN  1.889585  0.768839
2013-01-02       NaN  1.980355  0.087232  0.257254
2013-01-03  0.793269  0.813440  0.397283       NaN
2013-01-04  0.456985       NaN  0.705465  0.239551
2013-01-05       NaN  1.096913       NaN       NaN
2013-01-06  0.580815  1.291639       NaN  1.049427

In [ ]:
df2

                   A         B         C         D      E
2013-01-01  2.438309 -0.533176  1.889585  0.768839    one
2013-01-02 -1.278178  1.980355  0.087232  0.257254    one
2013-01-03  0.793269  0.813440  0.397283 -0.549010    two
2013-01-04  0.456985 -1.824791  0.705465  0.239551  three
2013-01-05 -0.909268  1.096913 -0.731259 -0.887379   four
2013-01-06  0.580815  1.291639 -0.423542  1.049427  three

In [ ]:
df2 = df.copy()
df2["E"] = ["one", "one", "two", "three", "four", "three"]
df2

                   A         B         C         D      E
2013-01-01  2.438309 -0.533176  1.889585  0.768839    one
2013-01-02 -1.278178  1.980355  0.087232  0.257254    one
2013-01-03  0.793269  0.813440  0.397283 -0.549010    two
2013-01-04  0.456985 -1.824791  0.705465  0.239551  three
2013-01-05 -0.909268  1.096913 -0.731259 -0.887379   four
2013-01-06  0.580815  1.291639 -0.423542  1.049427  three

In [ ]:
df2[df2["E"].isin(["two", "four"])]

                   A         B         C         D     E
2013-01-03  0.793269  0.813440  0.397283 -0.549010   two
2013-01-05 -0.909268  1.096913 -0.731259 -0.887379  four